<h1> 目的 </h1>

配列に関するコマンドをまとめたノートブックです。 配列そのものは適当に作成しています。  
思いつきで適宜追記をしていくかもしれません。

<h1> Python List </h1>

特にモジュールなどをインポートする必要はなく、そのまま使えます。  
格納された数値に対して何らかの計算等を行う場合は後述する Numpy の ndarray の方が便利です。

<h2> Make new lists </h2>

In [1]:
# 1-D array
arr_1d = [ i+j for i in range(0, 9, 1) for j in range(0, 900, 100) ]

# result
print(arr_1d)
print("Length : ", len(arr_1d))

[0, 100, 200, 300, 400, 500, 600, 700, 800, 1, 101, 201, 301, 401, 501, 601, 701, 801, 2, 102, 202, 302, 402, 502, 602, 702, 802, 3, 103, 203, 303, 403, 503, 603, 703, 803, 4, 104, 204, 304, 404, 504, 604, 704, 804, 5, 105, 205, 305, 405, 505, 605, 705, 805, 6, 106, 206, 306, 406, 506, 606, 706, 806, 7, 107, 207, 307, 407, 507, 607, 707, 807, 8, 108, 208, 308, 408, 508, 608, 708, 808]
Length :  81


In [2]:
# 2-D array
arr_2d = [[int(arr_1d[i]/100), arr_1d[i]] for i in range(len(arr_1d))]

# result
print(arr_2d)
print("Element : ", [len(v) for v in arr_2d])

[[0, 0], [1, 100], [2, 200], [3, 300], [4, 400], [5, 500], [6, 600], [7, 700], [8, 800], [0, 1], [1, 101], [2, 201], [3, 301], [4, 401], [5, 501], [6, 601], [7, 701], [8, 801], [0, 2], [1, 102], [2, 202], [3, 302], [4, 402], [5, 502], [6, 602], [7, 702], [8, 802], [0, 3], [1, 103], [2, 203], [3, 303], [4, 403], [5, 503], [6, 603], [7, 703], [8, 803], [0, 4], [1, 104], [2, 204], [3, 304], [4, 404], [5, 504], [6, 604], [7, 704], [8, 804], [0, 5], [1, 105], [2, 205], [3, 305], [4, 405], [5, 505], [6, 605], [7, 705], [8, 805], [0, 6], [1, 106], [2, 206], [3, 306], [4, 406], [5, 506], [6, 606], [7, 706], [8, 806], [0, 7], [1, 107], [2, 207], [3, 307], [4, 407], [5, 507], [6, 607], [7, 707], [8, 807], [0, 8], [1, 108], [2, 208], [3, 308], [4, 408], [5, 508], [6, 608], [7, 708], [8, 808]]
Element :  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

<h1> Numpy ndarray </h1>

<h2> Modules </h2>

In [3]:
import numpy as np

<h2> Make new Numpy ndarray </h2>

ndarray は単一のデータ型しか持てないため、整数型と浮動小数点型の数字を混在させると浮動小数点型に統一される。

In [4]:
# 1-D array
ndarr_1d = np.array([ i for i in np.arange(1, 9, 1)], dtype='int32')

# contents
print(ndarr_1d)

# information
print( "Array information" )
print( "   - Dimension   :", ndarr_1d.ndim )
print( "   - Array Shape :", ndarr_1d.shape )
print( "   - Array Size  :", ndarr_1d.size )
print( "   - Array Data type :", ndarr_1d.dtype )

# Mathematical results
print( "Mathematical results" )
print( "   - Mean   : {0:.2f}".format(np.mean(ndarr_1d)) )
print( "   - Standard deviation : {0:.4f}".format(np.std(ndarr_1d)) )
print( "   - Median : {0:.2f}".format(np.median(ndarr_1d)) )
print( "   - Total  : {0:5d}".format(np.sum(ndarr_1d)) )

[1 2 3 4 5 6 7 8]
Array information
   - Dimension   : 1
   - Array Shape : (8,)
   - Array Size  : 8
   - Array Data type : int32
Mathematical results
   - Mean   : 4.50
   - Standard deviation : 2.2913
   - Median : 4.50
   - Total  :    36


In [5]:
# 2-D array
ndarr_2d = np.array([ [i, i*10.0] for i in np.arange(1, 10, 1)], dtype=np.float32)

# contents
print(ndarr_2d)

# information
print( "Array information" )
print( "   - Dimension   :", ndarr_2d.ndim )
print( "   - Array Shape :", ndarr_2d.shape )
print( "   - Array Size  :", ndarr_2d.size )
print( "   - Array Data type :", ndarr_2d.dtype )

# Mathematical results
print( "Mathematical results" )
print( "   - Mean   : {0:.2f}".format(np.mean(ndarr_2d)) )
print( "   - Standard deviation : {0:.4f}".format(np.std(ndarr_2d)) )
print( "   - Median : {0:.2f}".format(np.median(ndarr_2d)) )
print( "   - Total  : {0:5.0f}".format(np.sum(ndarr_2d)) )

[[ 1. 10.]
 [ 2. 20.]
 [ 3. 30.]
 [ 4. 40.]
 [ 5. 50.]
 [ 6. 60.]
 [ 7. 70.]
 [ 8. 80.]
 [ 9. 90.]]
Array information
   - Dimension   : 2
   - Array Shape : (9, 2)
   - Array Size  : 18
   - Array Data type : float32
Mathematical results
   - Mean   : 27.50
   - Standard deviation : 29.0330
   - Median : 9.50
   - Total  :   495


<h2> Stack 2-D array (impossible to extend dimension) </h2>

2-D array を 2 つ合体させて 1 つの大きな 2-D array を作成する。  
concatenate では 1-D array を合体させることはできないので注意。  
1-D array の合体は次の項目を参照。

In [6]:
# test array
ndarr1 = np.array([[0,1], [2,3], [4,5]])
ndarr2 = np.array([[10,11], [12,13], [14,15]])

# result
print(ndarr1)
print(ndarr2)

[[0 1]
 [2 3]
 [4 5]]
[[10 11]
 [12 13]
 [14 15]]


In [7]:
# 縦に足し合わせる (vertical stack)
vertical_2d = np.concatenate([ndarr1, ndarr2], 0)

# contents
print(vertical_2d)

# information
print( "Array information" )
print( "   - Dimension   :", vertical_2d.ndim )
print( "   - Array Shape :", vertical_2d.shape )
print( "   - Array Size  :", vertical_2d.size )
print( "   - Array Data type :", vertical_2d.dtype )

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [10 11]
 [12 13]
 [14 15]]
Array information
   - Dimension   : 2
   - Array Shape : (6, 2)
   - Array Size  : 12
   - Array Data type : int64


In [8]:
# 横に足し合わせる (horizontal stack)
horizontal_2d = np.concatenate([ndarr1, ndarr2], 1)

# contents
print(horizontal_2d)

# information
print( "Array information" )
print( "   - Dimension   :", horizontal_2d.ndim )
print( "   - Array Shape :", horizontal_2d.shape )
print( "   - Array Size  :", horizontal_2d.size )
print( "   - Array Data type :", horizontal_2d.dtype )

[[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]]
Array information
   - Dimension   : 2
   - Array Shape : (3, 4)
   - Array Size  : 12
   - Array Data type : int64


<h2> Stack 1-D array as 2-D array (make new dimension) </h2>

1-D array を合体させて 1 つの新しい 2-D array を作る。  
1-D と 2-D の足し合わせは stack でもできない。  
その場合は次の項目のように 1-D array を一度 2-D array の形に変換をしてから行う。

In [9]:
# test array
ndarr3 = np.array([0,1,2,3,4,5])
ndarr4 = np.array([10,11,12,13,14,15])

# result
print(ndarr3)
print(ndarr4)

[0 1 2 3 4 5]
[10 11 12 13 14 15]


In [10]:
# 縦に stack する
verstack_2d = np.stack([ndarr3, ndarr4], 0)

# contents
print(verstack_2d)

# information
print( "Array information" )
print( "   - Dimension   :", verstack_2d.ndim )
print( "   - Array Shape :", verstack_2d.shape )
print( "   - Array Size  :", verstack_2d.size )
print( "   - Array Data type :", verstack_2d.dtype )

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]]
Array information
   - Dimension   : 2
   - Array Shape : (2, 6)
   - Array Size  : 12
   - Array Data type : int64


In [11]:
# 横に stack する
horstack_2d = np.stack([ndarr3, ndarr4], 1)

# contents
print(horstack_2d)

# information
print( "Array information" )
print( "   - Dimension   :", horstack_2d.ndim )
print( "   - Array Shape :", horstack_2d.shape )
print( "   - Array Size  :", horstack_2d.size )
print( "   - Array Data type :", horstack_2d.dtype )

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]
Array information
   - Dimension   : 2
   - Array Shape : (6, 2)
   - Array Size  : 12
   - Array Data type : int64


<h2> Stack 1-D array and 2-D array </h2>

1-D array と 2-D array の stack は、先に 1-D array に変換が必要。

In [12]:
# test array
ndarr5 = np.array([0,1,2])
ndarr6 = np.array([[10,11,12],[20,21,22], [30,31,32]])

# result
print(ndarr5)
print(ndarr6)

[0 1 2]
[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [13]:
# 縦に合体させる (1-D array の方を [] で囲う)
ver1d2d_2d = np.concatenate([[ndarr5], ndarr6], 0)

# contents
print(ver1d2d_2d)

# information
print( "Array information" )
print( "   - Dimension   :", ver1d2d_2d.ndim )
print( "   - Array Shape :", ver1d2d_2d.shape )
print( "   - Array Size  :", ver1d2d_2d.size )
print( "   - Array Data type :", ver1d2d_2d.dtype )

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
Array information
   - Dimension   : 2
   - Array Shape : (4, 3)
   - Array Size  : 12
   - Array Data type : int64


In [14]:
# 1-D array を reshape を使って変換 (方法1; -1=NR, 1=col を表す)
ndarr5_resh = ndarr5.reshape(-1, 1)

# 横に合体させる
reshape_2d = np.concatenate([ndarr5_resh, ndarr6], 1)

# contents
print(reshape_2d)

# information
print( "Array information" )
print( "   - Dimension   :", reshape_2d.ndim )
print( "   - Array Shape :", reshape_2d.shape )
print( "   - Array Size  :", reshape_2d.size )
print( "   - Array Data type :", reshape_2d.dtype )

[[ 0 10 11 12]
 [ 1 20 21 22]
 [ 2 30 31 32]]
Array information
   - Dimension   : 2
   - Array Shape : (3, 4)
   - Array Size  : 12
   - Array Data type : int64


In [15]:
# 1-D array を matrix を使って変換 (方法2)
ndarr5_mat = np.matrix(ndarr5).T

# 横に合体させる
matrix_2d = np.concatenate([ndarr5_mat, ndarr6], 1)

# contents
print(matrix_2d)

# information
print( "Array information" )
print( "   - Dimension   :", matrix_2d.ndim )
print( "   - Array Shape :", matrix_2d.shape )
print( "   - Array Size  :", matrix_2d.size )
print( "   - Array Data type :", matrix_2d.dtype )

[[ 0 10 11 12]
 [ 1 20 21 22]
 [ 2 30 31 32]]
Array information
   - Dimension   : 2
   - Array Shape : (3, 4)
   - Array Size  : 12
   - Array Data type : int64
